<?php 
	require_once('Config/Database.php');
	require_once(__ROOT__.'/header.php'); ?>
<!-- CONTENT HERE -->
	<br />
	<div class="container">
		<h1 class="h1-single"><strong>XML Sitemap</strong></h1>
		<p>Generated by portsignSEO, this is an XML Sitemap, meant for consumption by search engines.</p>
		<p>You can find more information about XML sitemaps on portsign.org.</p>
		<p>This XML Sitemap Index file contains 4 sitemaps.</p>
		<div class="custom-hr"><i>Back to Main Sitemap Page? <a href="<?php echo $baseurl; ?>sitemap.xml" class="btn btn-default btn-xs">Back</a></i></div>

		<div class="table-responsive">

            <table id="mytable" class="table table-bordred table-striped">
                  <thead>

               		<th>URL</th>
                    <th>Prio</th>
                    <th>Images</th>
                    <th>Ch. Freq.</th>
               		<th>Last Modified</th>

                  </thead>
                  <tbody>
                    <tr>
                        <td><a target="_blank" href="<?php echo $baseurl; ?>"><?php echo $baseurl; ?></a></td>
                        <td>100%</td>
                        <td>20</td>
                        <td>Daily</td>
                        <td>-</td>
                    </tr>
                   	<?php 
                        $showSitePost = mysqli_query($connecDB, "SELECT * FROM data_post ORDER BY id DESC LIMIT 6666");
                        while($z = mysqli_fetch_array($showSitePost)) {
                    ?>	

                            <tr>
                   			    <td><a target="_blank" href="<?php echo $baseurl.$z['slug'].".html"; ?>"><?php echo $baseurl.$z['slug'].".html"; ?></a></td>
                                <td>60%</td>
                                <td>9</td>
                                <td>Daily</td>
                   			    <td><?php echo $z['time']; ?></td>
                   		    </tr>

                    <?php } ?>
                  </tbody>
			</table>
                
        </div>
	</div>
</div>
<!-- END OF CONTENT HERE -->
</div>
</div>
</body>
</html>