<?php 
	require_once('Config/Database.php');
	require_once('header.php'); ?>
<!-- CONTENT HERE -->
	<br />
	<div class="container">
		<h1 class="h1-single"><strong>XML Sitemap</strong></h1>
		<p>Generated by portsignSEO, this is an XML Sitemap, meant for consumption by search engines.</p>

		<p>You can find more information about XML sitemaps on portsign.org.</p>

		<p>This XML Sitemap Index file contains 4 sitemaps.</p>
		<div class="custom-hr"></div>

		<div class="table-responsive">

            <table id="mytable" class="table table-bordred table-striped">
                   <thead>

                   		<th>Sitemap</th>
                   		<th>Last Modified</th>

                   </thead>
                   <tbody>
                   		<tr>
                   			<td><a href="<?php echo $baseurl; ?>post-sitemap.xml"><?php echo $baseurl; ?>post-sitemap.xml</a></td>
                   			<td>2015-12-24 05:14</td>
                   		</tr>
                   </tbody>
			</table>
                
        </div>
	</div>
</div>
<!-- END OF CONTENT HERE -->
</div>
</div>
</body>
</html>